version: '3'

services:
    web:
        image: nginx:latest
        ports:
            - "8080:80"
        links:
            - php
            - redis
        volumes:
            - ./..:/code
            - ./nginx.conf.d/backend.local.conf:/etc/nginx/conf.d/default.conf
            
    php:
        build: './php'
        links:
            - redis
        volumes:
            - ./..:/code
            - ./../.docker/.gnupg:/var/www/.gnupg
            - phpstan_cache:/tmp/phpstan
        environment:
            XDEBUG_CONFIG: "client_host=host.docker.internal discover_client_host=1"
            PHP_IDE_CONFIG: "serverName=Docker"

    cron:
        build: './php'
        links:
            - redis
        volumes:
            - ./..:/code
            - ./../.docker/.gnupg:/var/www/.gnupg
        entrypoint: [
                "bash",
                "-c",
                "cron
                && tail -f /var/log/cron.log"
        ]

    redis:
        hostname: rediscache
        image: 'docker.io/bitnami/redis:6.2-debian-10'
        environment:
            # ALLOW_EMPTY_PASSWORD is recommended only for development.
            - ALLOW_EMPTY_PASSWORD=yes
            #- REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
        ports:
            - '6379:6379'
        volumes:
            - 'redis_data:/bitnami/redis/data'

    redis-commander:
        container_name: redis-commander
        hostname: redis-commander
        image: rediscommander/redis-commander:latest
        links:
            - redis
        environment:
            - REDIS_HOSTS=local:rediscache:6379
        ports:
            - "8082:8081"

    user-api-docs:
        container_name: user-api-docs
        hostname: user-api-docs
        restart: always
        build:
            context: './../user_api_docs'
            dockerfile: '../.docker/user_api_docs/Dockerfile'
        ports:
            - "32754:8080"
        volumes:
            - ./../user_api_docs:/docs

    admin-api-docs:
        container_name: admin-api-docs
        hostname: admin-api-docs
        restart: always
        build:
            context: './../admin_api_docs'
            dockerfile: '../.docker/user_api_docs/Dockerfile'
        ports:
            - "32756:8080"
        volumes:
            - ./../admin_api_docs:/docs

volumes:
    redis_data:
        driver: local
    phpstan_cache:
        driver: local
# inspired by https://blog.denisbondar.com/post/phpstorm_docker_xdebug
